

@startuml TaskList


class App{

    -tareas:Tarea[]

    +crearTarea():Tarea
    +editarTarea(tarea:Tarea,parametro:parametroTarea,valor:??):void
    +eliminarTarea(tarea:Tarea):void
    +ordenarTareas(tareas:Tarea[]):void
    +buscarTareaPor(tarea:Tarea,valorAbuscar): Tarea


    +organizarTareasPorCategoria():Tarea
    
    +existeTarea (tarea:Tarea):bool
}

class GestorDeArchivos{

}

class Estadistica{

    -gestorDeFechas: GestorDeFechas

    +tareasCompletadas(tareas:Tarea[]): Tarea[]
    +tareasPendientes(tareas:Tarea[]): Tarea[]
    -filtrarPorEstadoTareas(tareas: Tarea[],filtro : string) : Tarea[]

    +tazaFinalizacionTareas(tareas:Tarea[]) : number
    +tazaFinalizacionTarea(tarea:Tarea): number
    +tiempoDedicadoATarea(tarea:Tarea): number

}

class GestorDeFechas {
    +diaFecha(fecha:Date):Number
    +mesFecha(fecha:Date):Number
    +añoFecha(fecha:Date):Number
    +capturarFechaActual():Date
    +nuevaFecha(dia:number,mes:number,año:number):Date
    +tiempoTranscurridoEnMilisegundos(fechaInicio:Date):number
    
    //+Funciones De conversiones

    }

enum EstadoTarea{
    COMPLETADO
    PENDIENTE
}

enum PrioridadTarea{
    ALTA
    MEDIA
    BAJA
}

enum TipoCategoria{
    TRABAJO 
    RECADO
    PERSONAL
}

class Tarea {
    
    -titulo:string
    -descripcion:string
    -porcentajeAvance:number
    -prioridad:Prioridad
    -etiquetas:Etiqueta[] 
    -estado: number
    -fechaVencimientoTarea: Date
    -estadoTarea: EstadoTarea
    -prioridadTarea: PrioridadTarea

    +setterGetters()
    
    +añadirEtiqueta(etiqueta:Etiqueta):void
    +eliminarEtiqueta(etiqueta:Etiqueta):void
    +marcarTareaCompleta():void
}


class Etiqueta { 
    -Id : number

}

abstract class Categoria extends Etiqueta {
    -categoria : TipoCategoria
    +añadirCategoriaTarea (tarea : Tarea) : void
}

Class CatTrabajo extends Categoria{
    -categoria = categoria.TRABAJO
}

Class CatRecado extends Categoria{
    -categoria = categoria.RECADO
}

Class Personal extends Categoria{
    -categoria = categoria.PERSONAL
}


'Relaciones

App *-right- Tarea
App *-left- Estadistica
App -down-> GestorDeArchivos

Tarea -up-> PrioridadTarea
Tarea -up-> EstadoTarea
Tarea -down->Etiqueta

Categoria -right-> TipoCategoria

Estadistica -down-> GestorDeFechas 

note left of Etiqueta
    ver de reformular
end note

note right of Etiqueta::Id
    servira?
end note

note right of Tarea::etiquetas
    set
end note



@enduml